//Tasks
export const TOGGLE_TASKLIST = "TOGGLE_TASKLIST";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const TOGGLE_CHECK = "TOGGLE_CHECK";
export const ACTIVE_TASK = "ACTIVE_TASK";
export const EDIT_TITLE_TASK = "EDIT_TITLE_TASK";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const ADD_TAG = "ADD_TAG";
export const DELETE_TAG = "DELETE_TAG";
export const SORT_TASKS = "SORT_TASKS";

export const FETCH_TASKS_START = "FETCH_TASKS_START";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILED = "FETCH_TASKS_FAILED";

export const PUSH_TASK_START = "PUSH_TASK_START";
export const PUSH_TASK_SUCCESS = "PUSH_TASK_SUCCESS";
export const PUSH_TASK_FAILED = "PUSH_TASK_FAILED";

//Auth
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

//Trash
export const ADD_TO_TRASH = "ADD_TO_TRASH";
export const FETCH_TRASH_START = "FETCH_TRASH_START";
export const FETCH_TRASH_SUCCESS = "FETCH_TRASH_SUCCESS";
export const FETCH_TRASH_FAILED = "FETCH_TRASH_FAILED";
